fix: add `Cargo.lock`
Some "minor" recent update in one or more dependencies apparently broke the build due to
the lack of committed `Cargo.lock`.

https://github.com/emqx/emqx/actions/runs/17079648621/job/48430349957?pr=15746#step:5:333

```
 error[E0423]: expected value, found struct `TimeoutInstant`
  --> /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot_core-0.9.11/src/parking_lot.rs:29:17
   |
29 |                 TimeoutInstant
   |                 ^^^^^^^^^^^^^^ constructor is not visible here due to private fields

error[E0423]: expected value, found struct `TimeoutInstant`
  --> /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot_core-0.9.11/src/parking_lot.rs:35:17
   |
35 |                 TimeoutInstant
   |                 ^^^^^^^^^^^^^^ constructor is not visible here due to private fields

error[E0117]: only traits defined in the current crate can be implemented for types defined outside of the crate
  --> /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot_core-0.9.11/src/parking_lot.rs:32:9
   |
32 |         impl core::ops::Add<Duration> for TimeoutInstant {
   |         ^^^^^------------------------^^^^^--------------
   |              |                            |
   |              |                            `Instant` is not defined in the current crate
   |              `Duration` is not defined in the current crate
   |
   = note: impl doesn't have any local type before any uncovered type parameters
   = note: for more information see https://doc.rust-lang.org/reference/items/implementations.html#orphan-rules
   = note: define and implement a trait or new type instead

error[E0116]: cannot define inherent `impl` for a type outside of the crate where the type is defined
  --> /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/parking_lot_core-0.9.11/src/parking_lot.rs:27:9
   |
27 |         impl TimeoutInstant {
   |         ^^^^^^^^^^^^^^^^^^^ impl for type defined outside of crate
   |
   = note: define and implement a trait or new type instead

   Compiling futures-channel v0.3.31
```